version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    ports:
    - 9200:9200
    environment:
      discovery.type: single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    ports:
    - 5601:5601
    restart: on-failure
    depends_on:
      - elasticsearch
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.7.0
    volumes:
    - ./filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro
    - /var/lib/docker/containers:/var/lib/docker/containers:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
    user: root
    restart: on-failure
  jms:
    image: vromero/activemq-artemis
    ports:
    - 8161:8161
    - 61616:61616
  zipkin:
    image: openzipkin/zipkin
    ports:
    - 9411:9411
  eureka:
    image: wle44beerwork/mssc-brewery-eureka
    ports:
    - 8761:8761
  config:
    image: wle44beerwork/mssc-config-server
    ports:
    - 8888:8888
    depends_on:
      - eureka
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
  inventory-service:
    image: wle44beerwork/mssc-beer-inventory-service
    ports:
    - 8082:8082
    depends_on:
      - eureka
      - config
      - jms
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://netflix:eureka@eureka:8761/eureka/
      SPRING_PROFILES_ACTIVE: local-discovery,localmysql
      SPRING_ZIPKIN_BASEURL: http://zipkin
      SPRING_ARTEMIS_HOST: jms
      SPRING_DATASOURCE_URL: jdbc:mysql://host.docker.internal:3306/beerinventoryservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      EUREAK_INSTANCE_PREFER_IP_ADDRESS: 'true'
    restart: on-failure
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"